### ISSUE TITLE
US 02.02.02: Allow organizers to see on a map where entrants joined their event waiting list from

### ISSUE THREAD

**Issue by skald1311** [CMPUT301F24iconic/iconic-RaffleEvent#20]
**Details:** As an organizer, I want to see on a map where entrants joined my event waiting list from

**Requirement:**
&nbsp;&nbsp;&nbsp;&nbsp;- When a user signs up for an event, get their location (only country? or rough exact location?) and store that along side their info in the waiting list
&nbsp;&nbsp;&nbsp;&nbsp;- If only country, have 1 marker in each of the countries where there're entrants, and pressing on it would display the entrants who registered from there
&nbsp;&nbsp;&nbsp;&nbsp;- If rough exact location, have 1 marker for each entrants

**Comment by AidenTeal** [comment]
Finished Implementation:
Shows entrant geopoints on a map using markers. The marker titles are the names of the users.
Implemented deletion of location if users leave waitlist or get cancelled by organizer.
