### ISSUE TITLE
US 02.05.01: Allow organizers to send a notification to chosen entrants to sign up for events

### ISSUE THREAD

**Issue by skald1311** [CMPUT301F24iconic/iconic-RaffleEvent#24]
**Details:** As an organizer, I want to send a notification to chosen entrants to sign up for events

**Requirement:**
&nbsp;&nbsp;&nbsp;&nbsp;- After the raffle ended, 2 options: either automatically send notifications to chosen entrants OR have a button for organizers so they can send it whenever

**Comment by AidenTeal** [comment]
Finished implementation, closing issue
