### ISSUE TITLE
US 02.07.01: Allow organizers to send notifications to all entrants on the waiting list

### ISSUE THREAD

**Issue by skald1311** [CMPUT301F24iconic/iconic-RaffleEvent#31]
**Details:** As an organizer, I want to send notifications to all entrants on the waiting list

**In this task, only implement the waiting list option**

**Requirement:**
&nbsp;&nbsp;&nbsp;&nbsp;- Need further clarification but assuming the notification is customizable and is whatever the organizer wants
&nbsp;&nbsp;&nbsp;&nbsp;- Have a page for creating a notification
&nbsp;&nbsp;&nbsp;&nbsp;- Should also have the desired receiver of the notification options as we also need it in US 02.07.02 and 02.07.03
&nbsp;&nbsp;&nbsp;&nbsp;- Receiver options: waiting list, selected entrants, canceled entrants

**Comment by AidenTeal** [comment]
Finished implementation, closing issue
