### ISSUE TITLE
US 02.07.03: Allow organizers to send a notification to all canceled entrants

### ISSUE THREAD

**Issue by skald1311** [CMPUT301F24iconic/iconic-RaffleEvent#33]
**Details:** As an organizer, I want to send a notification to all canceled entrants

Linked to US 02.07.01. **Should be done after US 02.07.01**

**Only implement the all canceled entrants option in this task**

**Requirement:**
&nbsp;&nbsp;&nbsp;&nbsp;- This should be one of the option in the receiver selection section (see US 02.07.01 for more details)

**Comment by AidenTeal** [comment]
Finished implementation, closing issue
