### ISSUE TITLE
US 01.03.03: Entrant's profile picture are deterministically generated from their profile name (if no picture yet)

### ISSUE THREAD

**Issue by ZHIYUA15** [CMPUT301F24iconic/iconic-RaffleEvent#7]
**Details:** As an entrant, I want my profile picture to be _deterministically generated_ from my profile name if I haven't uploaded a profile image yet.

**Requirement:**
&nbsp;&nbsp;&nbsp;&nbsp;- Should be done automatically on account creation
&nbsp;&nbsp;&nbsp;&nbsp;- Algorithm to deterministically generate picture? (not clear yet)

**Comment by skald1311** [comment]
[ui-avatars](https://ui-avatars.com/)
